runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"
# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 2

network:
  name: projects/prj-uat-host/global/networks/vpc-uat-shared-host-01
  subnetwork_name: sb-uat-as1-srv-wr-02

handlers:
  - url: /.*y
    script: auto
    secure: always
