import Link from "next/link";

export default function TermsAndConditions() {
  return (
    <div className="container mx-auto text-gray-100 text-sm mt-3">
      <h1 className="text-2xl text-center text-spiroDiscoBall font-bold mt-10">
        TERMS AND CONDITIONS
      </h1>
      <p className="my-4 text-gray-300">
        THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF THE INFORMATION
        TECHNOLOGY ACT, 2000 AND RULES MADE THEREUNDER . THIS ELECTRONIC RECORD
        IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR
        DIGITAL SIGNATURES. THESE TERMS ANDCONDITIONS (HEREINAFTER REFERRED TO
        AS &ldquo;T&amp;Cs&rdquo;) WERE UPDATED ON [--] . PLEASE CAREFULLY READ THESE T&amp;Cs . BY
        USING THIS PLATFORM YOU INDICATE YOUR UNDERSTANDING AND ACCEPTANCE OF
        THESE T&amp;Cs. IF YOU DO NOT AGREE TO THESE T&amp;Cs YOU MAY NOT USE THIS
        PLATFORM.
      </p>
      <h3 className="font-semibold my-2">1. DEFINITIONS:</h3>
      <p>
        In addition to other words and expressions that may be defined elsewhere
        in these T&amp;Cs, unless the context otherwise requires, the following
        capitalized terms wherever used in these T&amp;Cs shall have the meanings as
        ascribed hereunder:
      </p>
      <ul>
        <li className="my-1 ml-4">
          (a) &ldquo;Services&rdquo; shall mean and refer to various services including but
          not limited to providing access to information primarily about
          Financial and Insurance products including but not restricted to
          Health Insurance, General Insurance, Life Insurance, Vehicle
          Insurance, mutual funds, fixed deposits and related services that are/
          would be offered by the Company through the Platform.
        </li>
        <li className="my-1 ml-4">
          (b) &ldquo;Intellectual Property Rights&rdquo; shall mean any and all intellectual
          property rights belonging to and/or owned, used by a person in any
          parts of the world, whether registered or unregistered, including
          without limitation: (i) patents (whether utility or design); (ii)
          trademarks, service marks, logos, trade names and corporate names and
          the goodwill of the business symbolized; (iii) copyrights and
          copyrighted works; (iv) computer software, source code, data and
          documentation; (v) inventions, trade secrets, know-how, business
          intelligence and business information, whether patentable or
          non-patentable and whether or not reduced to practice; (vi)
          copyrightable works, specifications, etc., both printed and in
          electronic form; and (j) copies and tangible embodiments thereof.
        </li>
        <li className="my-1 ml-4">
          (c) &ldquo;Privacy Policy&rdquo; shall mean the privacy policy issued by the
          Company available on [•].
        </li>
        <li className="my-1 ml-4">
          (d) &ldquo;Users&rdquo;, &ldquo;You&rdquo; or &ldquo;Your&rdquo;; shall mean any natural or legal person
          who has access to and is using the Platform for the purpose of
          availing the Services offered by the Company in accordance with these
          T&amp;Cs. The term &ldquo;Users&rdquo; &ldquo;You&rdquo; or &ldquo;Your&rdquo; shall mean and include any
          other persons/entity who has not created a User Account and are
          accessing the Platform without such a User Account; and
        </li>
        <li className="my-1 ml-4">
          (e) &ldquo;User Account&rdquo; shall be the account, which the Users shall be
          required to create with the Platform to avail the entire gamut of
          Services offered by it.
        </li>
      </ul>
      <h3 className="font-semibold my-2">2. INTRODUCTION:</h3>
      <ul>
        <li className="my-1 ml-4">
          (a) Fidential Insurance Brokers Private Limited is a company
          incorporated under the Companies Act 2013, having its registered
          office at 1701 B, 17th floor, One International Centre, Senapati Bapat
          Marg, Prabhadevi West, Mumbai, 400013 (&ldquo;Company&rdquo;; &ldquo;We&rdquo;; &ldquo;Our&rdquo;; &ldquo;Us&rdquo;;
          and &ldquo;WealthRight&rdquo;). We own and operate the website wealth-right.com
          (&ldquo;Website&rdquo;) and the mobile application for mobiles, smart devices and
          any other compatible device (&ldquo;Application&rdquo;) under this brand
          ‘WealthRight’ (collectively referred to as the &ldquo;Platform&rdquo; whereby We,
          through the Platform provide financial services and solutions in
          connection to Insurances and Investments and related services and
          products therein(&ldquo;Services&rdquo;), subject to terms and conditions
          indicated in this document and/or any part of the Platform.
        </li>
        <li className="my-1 ml-4">
          (b) The Company provides access to the Platform, including all
          information, tools and services available from this Platform including
          access to all the Services, conditioned upon Your acceptance of all
          terms, conditions, policies and notices stated here. The User’s use of
          the Platform and related Services, including but not limited to
          viewing information, acting on such information and the transactions
          that may be implemented through the Platform, is governed by and shall
          be subject to these T&amp;Cs the T&amp;Cs whereof are subject to change at any
          time, without prior notice to You. Any new features or tools which are
          added to the current Platform shall also be subject to the T&amp;Cs. To
          ensure that You are aware of the changes, please review these T&amp;Cs and
          all the documents referred to hereunder periodically.
        </li>
        <li className="my-1 ml-4">
          (c) If You continue to browse through this Platform, You are agreeing
          to be bound by the T&amp;Cs which along with the Privacy Policy, as
          displayed on the Platform, govern your relationship with Us. You
          confirm that You have also read and have agreed and accepted to be
          bound by the terms and conditions of the Privacy Policy, which shall
          be deemed to be a part of these T&amp;Cs
        </li>
        <li className="my-1 ml-4">
          (d) In the event You are representing an incorporated entity, You
          hereby confirm that You have been expressly authorised by such entity
          to consent these T&amp;Cs, and such entity agrees to be bound by the T&amp;Cs
          hereunder
        </li>
        <li className="my-1 ml-4">
          (e) These T&amp;Cs set forth the legally binding terms of Your use of the
          Platform and related services. By proceeding further, You confirm that
          You have read and have agreed and accepted to be bound by the T&amp;Cs
          mentioned herein and incorporated in any additional guidelines or
          rules applicable to particular services promulgated by the Company on
          the Platform that may be amended from time to time (&ldquo;Supplemental
          Terms&rdquo;), which shall be deemed to be a part of these T&amp;Cs. In the
          event of any conflict between the terms of these T&amp;Cs and any
          aforesaid Supplemental Terms, the Supplemental Terms shall prevail. If
          any of the terms of these T&amp;Cs or of any of the Supplemental Terms are
          not acceptable to You, please do not use the Platform. Your continued
          usage of the Platform after any change constitutes Your acceptance of
          the amended T&amp;Cs.
        </li>
        <li className="my-1 ml-4">
          (f) Kindly read the terms of these T&amp;Cs carefully before accessing or
          using the Platform or Services. These T&amp;Cs shall be legally binding on
          the Users.
        </li>
        <li className="my-1 ml-4">
          (g) These T&amp;Cs apply to all Users of the Platform, including without
          limitation users who are browsers, vendors, customers, and/ or
          contributors of data, content, information, pictorial representations
          and/or images.
        </li>
      </ul>
      <h3 className="font-semibold my-2">3. TERMS OF USE:</h3>
      <ul>
        <li className="my-1 ml-4">
          (a) The Company will provide Services to You subject to continuous
          compliance with the T&amp;Cs stipulated in this document. The Services are
          extended through the Platform that enables You to avail the Services
          provided by the Company on the Platform.
        </li>
        <li className="my-1 ml-4">
          (b) By using the Platform, you agree to comply with and be legally
          bound by the T&amp;Cs. These T&amp;Cs govern your access to and use of the
          Platform and Services and constitute a binding legal agreement between
          you and the Company.
        </li>
        <li className="my-1 ml-4">
          (c) If you do not agree to these T&amp;Cs, kindly do not access or use the
          Platform . The User can access the Services directly via the Platform.
        </li>
        <li className="my-1 ml-4">
          (d) You acknowledge and agree that, by accessing or using the Platform
          or Services or by availing any Services therein from the Platform, you
          are indicating that you have read, and that you understand and agree
          to be bound by these T&amp;Cs and receive our Services.
        </li>
        <li className="my-1 ml-4">
          (e) We reserve the right at any time to modify, suspend or discontinue
          the Service and/ or eliminate any aspect or features of the Platform
          or the Services (or any part or content thereof) as it deems fit,
          without notice at any time and shall not be held liable to any third
          party for such change or modification or discontinuation as specified
          hereinabove. The Company makes no commitment, express or implied, to
          maintain or continue any aspect of the Platform / Services. All prices
          are subject to change, as the Company may deem fit at any time. The
          Company will notify you about any change in the T&amp;Cs or the fees or
          the Services or features of Platforms, via any medium including notice
          on the Platform.
        </li>
        <li className="my-1 ml-4">
          (f) The Company may, based on any form of access to the Platform or
          Services or registrations, including free trials, through any source
          whatsoever, contact the User through SMS, e-mail and/or call, to give
          information about its products as well as notifications on various
          important updates and/or to seek permission for demonstration of its
          products and/or for marketing purposes. The User expressly grants such
          permission to contact him/her through telephone, SMS, e-mail. After
          the registration via the Platform, you acknowledge and agree that the
          employees of the Company or any person authorised by the Company in
          this regard, may contact you for the above mentioned purposes and
          promotional purposes through telephone, SMS, email etc. The Company
          shall have the right to monitor the download and usage of the
          Platform/ Services and the contents thereof by the User, as specified
          in the P rivacy P olicy of the Company in order to enable effective
          and efficient usage of the Services and access to improvised and
          customised Services.
        </li>
        <li className="my-1 ml-4">
          (g) The Company has taken the best efforts to train the personnel
          engaged in the sales and customer service departments, however it
          makes no warranties or representations whatsoever regarding the
          quality and competence of such personnel. The Company would not be
          responsible in any manner for any deviant behaviour of any such
          personnel. The User may give us a feedback about the services provided
          by such personnel and Company reserves the right and discretion to
          take any action in this regard.
        </li>
        <li className="my-1 ml-4">
          (h) The Platform and Services or any content, are compatible only with
          certain devices/tablets/instruments/hardware The Company shall not be
          obligated to provide workable products and / or services for any
          instruments that are not recognized by the Company or which are not
          compatible with the Company&apos;s products and Services. The Company
          reserves the right to upgrade the table/ type of compatible devices as
          it may deem fit from time to time.
        </li>
        <li className="my-1 ml-4">
          (i) The Company shall have no responsibility for any loss or damage
          caused to device or any other hardware and / or software and/or
          instrument, including loss of data or effect on the processing speed,
          resulting from your use of our Services.
        </li>
        <li className="my-1 ml-4">
          (j) The Platform can be accessed from countries around the world and
          may contain references to services and content that are not available
          in Your country. These references do not imply that Company intends to
          announce such services or content in Your country. The Platform and
          the Service are controlled and offered by Us from from India . Company
          makes no representations that the Platform or the Service are
          appropriate or available for use in other locations. Those who access
          or use the Platform or the Service from other jurisdictions do so at
          their own volition and are responsible for compliance with local laws
          of India .
        </li>
      </ul>
      <h3 className="font-semibold my-2">4. USER ELIGIBLITY:</h3>
      <ul>
        <li>
          The Platform and Services can be accessed and used by those
          individuals or business entities, including sole proprietorship firms,
          companies and partnerships, which can form legally binding contracts
          under the applicable law. Only individuals who are eighteen (18) years
          of age or older may use the Platform and avail Services. The Company
          reserves the right to terminate the User Account and / or deny access
          to the Platform if it is brought to the Company’s notice or if it is
          discovered that the User does not meet the conditions herein.
        </li>
      </ul>
      <h3 className="font-semibold my-2">5. USER CONDUCT:</h3>
      By agreeing to these T&amp;Cs,
      <ul>
        <li className="my-1 ml-4">
          (a) You represent that You are at least the age of majority in your
          state or province of residence and You have given Us the consent to
          allow any of Your minor dependents to use this Platform;
        </li>
        <li className="my-1 ml-4">
          (b) You will not use any of the Services for any illegal or
          unauthorized purpose. No User shall be permitted to perform any of the
          following prohibited activities while availing our Services:
          <ul>
            <li className="my-1 ml-8">
              i. u sing the Platform or Services for any unlawful purpose;
            </li>
            <li className="my-1 ml-8">
              ii. u se deep-links, page-scrape, robot, spider or other automatic
              device, program, algorithm or methodology, or any similar or
              equivalent manual process, to increase traffic to the Platform
              /Services, to access, acquire, copy or monitor any portion of the
              Platform/Services, or in any way reproduce or circumvent the
              navigational structure or presentation of the Platform , or any
              content, to obtain or attempt to obtain any content, documents or
              information through any means not specifically made available
              through the Platform /Services;
            </li>
            <li className="my-1 ml-8">
              iii. access or tamper, or attempt to do so, with any part of the
              Platform not open for public access;
            </li>
            <li className="my-1 ml-8">
              iv. to solicit others to perform or participate in any unlawful
              acts;
            </li>
            <li className="my-1 ml-8">
              v. to violate any international, national, federal, provincial or
              state regulations, rules, laws, directions, guidelines, circulars,
              order, judgement, ordinances or any other law issued by a
              competent government authority;
            </li>
            <li className="my-1 ml-8">
              vi. making, transmitting or storing electronic copies of materials
              protected by copyright without the permission of the owner,
              committing any act that amounts to infringement or violation of
              our I ntellectual P roperty R ights or the I ntellectual P roperty
              R ights of others;
            </li>
            <li className="my-1 ml-8">
              vii. to harass, abuse, insult, harm, defame, slander, disparage,
              intimidate, or discriminate based on gender, sexual orientation,
              religion, ethnicity, race, age, national origin, or disability;
            </li>
            <li className="my-1 ml-8">
              viii. to submit false or misleading information;
            </li>
            <li className="my-1 ml-8">
              ix. to post any obscene, pornographic, immoral or illegal content
              or post a link to such content;
            </li>
            <li className="my-1 ml-8">
              x. to embed any content form the Platform;
            </li>
            <li className="my-1 ml-8">
              xi. to upload or transmit viruses or any other type of malicious
              code that will or may be used in any way that will affect the
              functionality or operation of the Service or of any related
              Platform, other Platforms, or the internet;
            </li>
            <li className="my-1 ml-8">
              xii. to collect or track the personal information of others;
            </li>
            <li className="my-1 ml-8">
              xiii. to spam, phish, pharm, pretext, spider, crawl, or scrape;
            </li>
            <li className="my-1 ml-8">
              xiv. for any obscene or immoral purpose;
            </li>
            <li className="my-1 ml-8">
              xv. to interfere with or circumvent the security features of the
              Service or any related Platform, other p latforms, or the
              internet;
            </li>
            <li className="my-1 ml-8">
              xvi. impersonate any person or entity, or falsely state the
              details;
            </li>
            <li className="my-1 ml-8">
              xvii. interfere with, or inhibit any user from using and enjoying
              access to the Platform/ Services, or other affiliated sites, or
              engage in disruptive attacks such as denial of service attack on
              the Platform/Services;
            </li>
            <li className="my-1 ml-8">
              xviii. access or use the Platform/Services in any manner that
              could damage, disable, overburden or impair any of the Platform’s
              servers or the networks connected to any of the servers on which
              the Platform is hosted;
            </li>
            <li className="my-1 ml-8">
              xix. use the Platform/ Services for purposes that are not
              permitted by: (i) these T&amp;Cs;;
            </li>
            <li className="my-1 ml-8">
              xx. violate any of the terms specified under the T&amp;Cs for the use
              of the Platform/Services;
            </li>
            <li className="my-1 ml-8">
              xxi. use the Platform or Services, or any part thereof, for any
              commercial or for-profit use;
            </li>
            <li className="my-1 ml-8">
              xxii. alter, process, adapt, sublicense, decompile, reverse
              engineer, or disassemble the contents of the Platform and/or
              Services or modify, copy, distribute, transmit, display, perform,
              reproduce, publish, license, create derivative works from,
              transfer, or sell any information or software obtained from the
              Platform and/or Services, or remove any copyright, trademark
              registration, or other proprietary notices from the contents of
              the Platform and/or Services; or
            </li>
            <li className="my-1 ml-8">
              xxiii. reproduce, duplicate, copy, sell, resell or exploit any
              portion of the Service, use of the Service, or access to the
              Service or any contact on the Platform through which the Service
              is provided, without express written permission by Us.
            </li>
          </ul>
          We reserve the right to forthwith terminate Your use of the Service or
          any related Platform for violating any of the prohibited uses or any
          other terms specified herein.
        </li>
        <li className="my-1 ml-4">
          (c) You must not transmit any worms or viruses or any code of a
          destructive nature. Violations of system or network security may
          result in civil or criminal liability. You agree that it is your
          responsibility to install anti-virus software and related protections
          against viruses, Trojan horses, worms, time bombs, cancelbots, or
          other computer programming routines or engines that are intended to
          damage, destroy, disrupt, or otherwise impair a computer’s
          functionality or operation.
        </li>
        <li className="my-1 ml-4">
          (d) Any fraudulent use of this Platform or applicable payment method
          to avail the Services, which causes any monetary loss to the Company
          as a result of Your action/inaction shall be recovered from You.
          Without prejudice to the above, the Company reserves the right to
          initiate legal proceedings against You for the fraudulent use of this
          Platform or for any other unlawful act or omission in breach of these
          T&amp;Cs;
        </li>
        <li className="my-1 ml-4">
          (e) The images and pictorial representations on the Platform may be
          enhanced for advertising purposes;
        </li>
        <li className="my-1 ml-4">
          (f) You also understand and acknowledge that the use of the Platform
          requires internet /mobile network connectivity. You shall bear the
          costs incurred to access and use the Platform and We shall not, under
          any circumstances whatsoever, be responsible or liable for such costs;
        </li>
        <li className="my-1 ml-4">
          (g) It is the sole responsibility of the User to ensure that the
          account information provided by the User is accurate, complete and
          latest.
        </li>
        <li className="my-1 ml-4">
          (h) You shall be solely responsible for all activities undertaken
          through Your User Account, whether or not You have authorized such
          activities or actions and shall, at all times, keep the Company
          indemnified in this regard;
        </li>
        <li className="my-1 ml-4">
          (i) A breach or violation of any of the terms of T&amp;Cs will result in
          an immediate termination of Services and may result in reporting to
          the law enforcement agencies (if deemed necessary by the Company).
        </li>
        <li className="my-1 ml-4">
          (j) We reserve the right to refuse Service to anyone (without
          assigning any reason) at any time, at our sole discretion.
        </li>
        <li className="my-1 ml-4">
          (k) Your content and information submitted by you on the Platform or
          any other information collected during your access of the Platform
          (not including credit card and other critical financial and personal
          information), may be transferred unencrypted and involve (a)
          transmissions over various networks; and (b) changes to conform and
          adapt to technical requirements of connecting networks or devices,
          subject to the terms and conditions specified under the Privacy
          Policy.
        </li>
        <li className="my-1 ml-4">
          (l) You acknowledge and agree that the accessibility to the Platform
          is dependent on multiple external factors such as internet service
          providers, location, bandwidth and the Company does not guarantee
          accessibility to the Platform at all times. In addition to the
          disclaimers and conditions set forth in the T&amp;Cs, the Company shall
          not be liable to the User for any damages arising from your inability
          to log into your account and access the Services provided via the
          Platform at any time.
        </li>
      </ul>
      <h3 className="font-semibold my-2">6. REGISTRATION:</h3>
      <ul>
        <li className="my-1 ml-4">
          (a) In order to avail the Services and access and use the Platform,
          the User shall be required to register himself/herself with the
          Platform and maintain a User Account and receive or establish a
          password (&ldquo;Password&rdquo;) which can be used by you or each of your
          employees and consultants who are authorized by you to use the
          Services on your behalf. Additionally, You will also have the option
          to use a single sign-in feature through Your email account to log-in
          without providing the Password.
        </li>
        <li className="my-1 ml-4">
          (b) The User will be required to furnish certain information and
          details, including his/her name, mobile number, e-mail address,
          residential address, and any other information deemed necessary for
          the purpose of registration.
        </li>
        <li className="my-1 ml-4">
          (c) In registering for the Service, you agree to provide true,
          accurate, current and complete information about yourself as prompted
          by our registration form (&ldquo;Registration Data&rdquo;) and to maintain and
          promptly update the Registration Data to keep it true, accurate,
          current and complete.
        </li>
        <li className="my-1 ml-4">
          (d) If you provide any Registration Data that is untrue, inaccurate,
          not complete or incomplete, or Company has reasonable grounds to
          suspect that such information is untrue, inaccurate, not current or
          incomplete, Company has the right to suspend or terminate your User
          Account and to refuse any and all current or future use of the Service
          (or any portion thereof) by you.
        </li>
        <li className="my-1 ml-4">
          (e) You are responsible for all activities that occur under your User
          Account and your Password. You agree to notify Company immediately of
          any unauthorized use of your User Account or Password or any other
          breach of security and to exit from your User Account at the end of
          each session. You agree that you are responsible for any losses
          arising out of the unauthorized use of Your User Account.
        </li>
        <li className="my-1 ml-4">
          (f) After registration, the User can access the Platform and avail the
          Services available via the Platform.
        </li>
        <li className="my-1 ml-4">
          (g) The User understands and acknowledges that there are certain
          Services which may be accessible only after registration with the
          Platform and creation of a User Account, in the manner specified
          above.
        </li>
        <li className="my-1 ml-4">
          (h) Each of the Services will be charged separately and the User shall
          pay for each component of such Service Service or product he/she
          wishes to avail as mentioned at the time of registration for availing
          the Services.
        </li>
        <li className="my-1 ml-4">
          (i) The User can access certain Services on the Platform via
          subscription services. In the event, the User opts for subscription
          services, the User shall pay for availing the services under the
          subscription plan either on a monthly or an annual basis, depending on
          the service plan availed by the User.
        </li>
      </ul>
      <h3 className="font-semibold my-2">7. FEES AND PAYMENT:</h3>
      <ul>
        <li className="my-1 ml-4">
          (a) The Company offers its Services via the Platform subject to the
          specified fees and charges. The User can access the Services available
          on the Platform only after payment of the fee/ charge as may be
          specified for the said Service.
        </li>
        <li className="my-1 ml-4">
          (b) The User opting for any subscription services will be responsible
          for payment of the applicable monthly/ quarterly/ annual fee at the
          time you create your Account and select your package. You can select
          and change a suitable subscription plan from Our Platform.
        </li>
        <li className="my-1 ml-4">
          (c) The Company shall collect the payment of fees for the said Service
          selected by the User via a third-party payment service provider
          platform. The Company will raise a system generated invoice and send
          it to the User via email or text message or any other medium,
          specifying the details of the said Service availed and the amount paid
          by the User.
        </li>
        <li className="my-1 ml-4">
          (d) All fees will be billed to the credit card, debit card or unified
          payments interface (&ldquo;UPI&rdquo;) account You designate during the
          registration process. In the alternate, if requested by You, You may
          also transfer the fees vide NEFT/ IMPS to Our designated bank account,
          which shall be informed to You.
        </li>
        <li className="my-1 ml-4">
          (e) The Company does not collect any information related to the
          payment method or related details of the Users and shall not be liable
          for any breach or actions related to the payment methods by the
          third-party payment platform provider.
        </li>
        <li className="my-1 ml-4">
          (f) The User shall read the privacy policy of the third-party payment
          platform provider prior to submitting any details related to the same.
        </li>
      </ul>
      <h3 className="font-semibold my-2">8. AUTO RENEWAL:</h3>
      <ul>
        <li className="my-1 ml-4">
          (a) In order to ensure that you do not experience an interruption or
          loss of Service, Services may be offered on automatic renewal basis
          which would automatically renew the applicable Service upon expiration
          of the then current term for a renewal period equal in time to the
          most recent Service period.
        </li>
        <li className="my-1 ml-4">
          (b) Unless you disable the automatic renewal option, company will
          automatically renew the applicable service when it comes up for
          renewal and will deduct the relevant fees from the payment method you
          have on file with Company at Company’s then current rates, which you
          acknowledge and agree may be higher or lower than the rates for the
          original Service period. In case of a change in the fee structure, the
          Company shall through its payment gateway or by themselves, intimate
          the same to You via email prior to such renewal. Please note that
          effective 1 October 2021, your bank may not be able to process any
          requests for automated payments on your credit / debit cards unless it
          complies with RBI’s e-mandate guidelines.
        </li>
        <li className="my-1 ml-4">
          (c) If You do not wish for any Service to automatically renew, You may
          elect to cancel renewal, in which case, Your Services will terminate
          upon expiration of the then current term, unless the relevant fee has
          been paid.
        </li>
      </ul>
      <h3 className="font-semibold my-2">9. CANCELLATION OF SERVICES</h3>
      <ul>
        <li className="my-1 ml-4">
          (a) As per the IRDAI rules and regulations, you have the right to
          cancel your insurance policy within 15(fifteen) days from the date of
          (online) receipt of insurance policy (referred to as &ldquo;Free look
          period&rdquo;) and refund of your premium amount shall be processed as per
          the applicable process and procedures followed by the insurer. This
          Free look facility can be availed only for Life and Health insurance
          policies, subject to certain other terms and conditions specified by
          IRDAI.
        </li>
        <li className="my-1 ml-4">
          (b) You agree that you will make any cancellation request by way of a
          general request ticket that you submit through the Company’s ticketing
          system or You may cancel Your subscription via the subscription URL
          provided by the payment processor. In the event that You are using an
          UPI account to make payments hereunder, You must also log in and
          cancel Your recurring payments via Your UPI interface.
        </li>
        <li className="my-1 ml-4">
          (c) You may, within thirty (30) days from the date of signing-up or
          thirty (30) days prior to the renewal date, cancel the annual/
          biannual service (the &ldquo;Cancellation Period&rdquo;), in which case the
          Company will refund your service subscription fee for the remaining
          Service Term . Further, in the event, You request for a cancellation,
          the refund will be made only for the period for which the Services
          were not used by You and such a refund would be made as per the then
          existing subscription charges even if You had availed the subscription
          at a discounted rate.
        </li>
        <li className="my-1 ml-4">
          (d) In the event the cancellation is initiated, the refund shall be
          initiated within a period of 7 (seven) working days, subject to the
          refund policy of the Company.
        </li>
        <li className="my-1 ml-4">
          (e) Except as set forth above, your service subscription fee shall be
          non-refundable. Further, no refund will be made in respect of Services
          already availed or provided. The Company will initiate any refunds due
          pursuant to the terms mentioned herein.
        </li>
        <li className="my-1 ml-4">
          (f) The Company reserves the right to cancel the provision of Services
          to any User at its sole discretion and the Company shall upon such
          cancellation pay as and by way of liquidated damages such User the
          fees that such User had paid the Company in the term prior to such
          cancelation by Us.
        </li>
        <li className="my-1 ml-4">
          (g) Further, you understand that once you place a cancellation request
          within the Free look period, the policy gets cancelled and entire
          premium is refunded to you subject to deduction of (i) charges
          pertaining to medical tests conducted (ii) administrative and service
          cost like stamp duty etc. and; (iii) Charges for mortality for the
          period the policy was in force. Please note such deduction is at the
          sole discretion of the insurer.
        </li>
        <li className="my-1 ml-4">
          (h) The Company reserves the right to suspend the provisions of
          Services or any part thereof to any User for reasons not limited to
          the following:
          <ul>
            <li className="my-1 ml-8">
              i. The Company has reason to believe that you have violated the
              T&amp;Cs or relevant law while using the Platform or availing the
              Service.
            </li>
            <li className="my-1 ml-8">
              ii. The Registration Data is not verifiable by us.
            </li>
            <li className="my-1 ml-8">
              iii. Your use of the Platform may lead to or has lead to financial
              loss, fraud, or reasonable risk of the same to the Company or any
              third party.
            </li>
          </ul>
        </li>
      </ul>
      <h3 className="font-semibold my-2">10. PUBLICITY</h3>
      <ul>
        <li>
          You grant us the right to add your name and company logo to our
          customer list and on Our Platform.
        </li>
      </ul>
      <h3 className="font-semibold my-2">
        11. ACCURACY, COMPLETENESS AND TIMELINESS OF INFORMATION:
      </h3>
      <ul>
        <li className="my-1 ml-4">
          (a) We are not responsible if information made available on the
          Platform is not accurate or not complete or not current . Any reliance
          on the material on the Platform is at Your own risk.
        </li>
        <li className="my-1 ml-4">
          (b) Occasionally there may be information on the Platform or in the
          Service that contains typographical errors, inaccuracies or omissions
          that may relate to Service descriptions, pricing, promotions, offers,
          transit times and availability. We reserve the right to correct any
          errors, inaccuracies or omissions, and to change or update information
          or cancel orders if any information in the Service or on any related
          Platform is inaccurate at any time without prior notice (including
          after You have submitted Your order).
        </li>
        <li className="my-1 ml-4">
          (c) We undertake no obligation to update, amend or clarify information
          in the Service or on any related Platform, including without
          limitation, pricing information, except as required by law. No
          specified update o should be taken to indicate that all information in
          the Service or on any related Platform has been modified or updated.
        </li>
        <li className="my-1 ml-4">
          (d) You acknowledge that such information and materials may contain
          inaccuracies or errors and we expressly exclude liability for any such
          inaccuracies or errors to the fullest extent permitted by law. This
          Platform and the Services are provided on an &quot;AS IS&quot; basis with all
          faults and without any warranty of any kind.
        </li>
      </ul>
      <h3 className="font-semibold my-2">
        12. MODIFICATIONS TO THE SERVICE AND PRICES:
      </h3>
      <ul>
        <li>
          We reserve the right at any time to modify, suspend or discontinue the
          Service and/ or eliminate any aspect or features of the Platform or
          the Services (or any part or content thereof) as it deems fit, without
          notice at any time and shall not be held liable to any third party for
          such change or modification or discontinuation as specified
          hereinabove. The Company makes no commitment, express or implied, to
          maintain or continue any aspect of the Platform / Services. All prices
          are subject to change, as the Company may deem fit at any time. The
          Company will notify you about any change in the T&amp;Cs or the fees or
          the Services or features of Platforms, via any medium including notice
          on the Platform.
        </li>
      </ul>
      <h3 className="font-semibold my-2">13. OPTIONAL TOOLS</h3>
      <ul>
        <li className="my-1 ml-4">
          (a) We may provide You with access to third-party tools which We
          neither monitor nor have any control over nor do We provide any input.
          You acknowledge and agree that we provide access to such tools on an
          &ldquo;as is basis&rdquo; and &ldquo;as available&rdquo; without any warranties,
          representations or conditions of any kind and without any endorsement.
          We shall have no liability whatsoever arising from or relating to your
          use of optional third-party tools.
        </li>
        <li className="my-1 ml-4">
          (b) Any use by You of optional tools offered through the Platform is
          entirely at Your own risk and discretion and You should ensure that
          You are familiar with and approve of the terms on which tools are
          provided by the relevant third-party provider(s). We may also, in the
          future, offer new services and/or features through the Platform
          (including, the release of new tools and resources)
        </li>
        <li className="my-1 ml-4">
          (c) Such new features and/or services shall also be subject to these
          T&amp;Cs.
        </li>
      </ul>
      <h3 className="font-semibold my-2">14. THIRD-PARTY LINKS:</h3>
      <ul>
        <li className="my-1 ml-4">
          (a) Certain content, products and services available via our Platform
          may include materials from third parties.
        </li>
        <li className="my-1 ml-4">
          (b) Third-party links on this Platform may direct You to third-party
          Platforms that are not affiliated with Us. We are not responsible for
          examining or evaluating the content or accuracy and We do not warrant
          and will not have any liability or responsibility for any third-party
          materials or Platforms, or for any other materials, products, or
          services of third-parties.
        </li>
        <li className="my-1 ml-4">
          (c) We are not liable for any harm or damages related to the purchase
          or use of goods, services, resources, content, or any other
          transactions made in connection with any third-party platforms. Please
          review carefully the third-party&apos;s policies and practices and make
          sure You understand them before You engage in any transaction.
          Complaints, claims, concerns, or questions regarding third-party
          products should be directed to the third-party.
        </li>
      </ul>
      <h3 className="font-semibold my-2">
        15. USER COMMENTS, FEEDBACK AND OTHER SUBMISSIONS:
      </h3>
      <ul>
        <li className="my-1 ml-4">
          (a) If, at Our request, You send certain specific submissions (for
          example contest entries) or without a request from Us, You send
          creative ideas, suggestions, proposals, plans, or other materials,
          whether online, by email, by postal mail, or otherwise (collectively,
            &ldquo;Comments&rdquo;), You agree that We may, at any time, without restriction,
          edit, copy, publish, distribute, translate and otherwise use in any
          medium any comments that You forward to Us.
        </li>
        <li className="my-1 ml-4">
          (b) We are and shall be under no obligation to:
          <ul>
            <li>i. maintain any Comments in confidence;</li>
            <li>ii. pay compensation or reimburse for any Comments; or</li>
            <li>iii. respond to any Comments.</li>
          </ul>
        </li>
        <li className="my-1 ml-4">
          (c) You agree that all your Comments shall be subject to this T&amp;Cs and
          any such communication shall be deemed to be use of the Platform..
        </li>
        <li className="my-1 ml-4">
          (d) Any feedback provided by the User with respect to the Platform
          shall be deemed to be non-confidential and may be used on an
          unrestricted basis to improve the quality of Services offered by the
          Company. Further, the User represents and warrants that (i) the
          feedback does not contain confidential or proprietary information of
          the User or of third parties; and (ii) the Company is not under any
          obligation of confidentiality, express or implied, with respect to the
          feedback
        </li>
        <li className="my-1 ml-4">
          (e) NOTWITHSTANDING ANY PROVISION OF THIS T&amp;Cs OR ANY OTHER DOCUMENT,
          YOU UNDERSTAND AND AGREE THAT E-MAIL COMMUNICATION IS NOT SECURE, AND
          THEREFORE YOU AGREE THAT YOU WILL USE THE COMPANY’S TICKETING SYSTEM
          TO EXCHANGE ALL CREDENTIALS, TECHNICAL INFORMATION AND SERVICE
          SPECIFIC SUPPORT REQUESTS .
        </li>
      </ul>
      <h3 className="font-semibold my-2">16. PERSONAL INFORMATION :</h3>
      <ul>
        <li>
          Your submission of personal information is governed by Our Privacy
          Policy&nbsp;
          <Link className="text-bondiBlue hover:text-spiroDiscoBall" href="/legal/privacy">www.wealth-right.com/legal/privacy</Link>,
          displayed on the Platform.
        </li>
      </ul>
      <h3 className="font-semibold my-2">
        17. DISCLAIMER OF WARRANTIES; LIMITATION OF LIABILITY:
      </h3>
      <ul>
        <li className="my-1 ml-4">
          (a) The content, products, and services featured on this Platform may
          contain inaccuracies or errors, including pricing errors. We do not
          guarantee the accuracy of the information and disclaim all liability
          for any errors or inaccuracies related to the content, products, and
          services. We reserve the right to correct pricing errors on the
          Site/Mobile Application and/or on pending reservations made under an
          incorrect price.
        </li>
        <li className="my-1 ml-4">
          (b) In no event shall WealthRight and/or its affiliates be liable for
          any direct, indirect, punitive, incidental, special, or consequential
          damages arising from your access to, display of, or use of this
          Platform. This includes delays or inability to access, display, or use
          the Platform, whether based on negligence, contract, tort, strict
          liability, or otherwise, even if WealthRight and/or its affiliates or
          service providers have been advised of the possibility of such
          damages.
        </li>
        <li className="my-1 ml-4">
          (c) We do not guarantee, represent or warrant that your use of our
          Service will be uninterrupted, timely, secure or error-free.
        </li>
        <li className="my-1 ml-4">
          (d) We do not warrant that the results that may be obtained from the
          use of the Service will be accurate or reliable. You agree that from
          time to time we may remove the Service for indefinite periods of time
          or cancel the Service at any time, without notice to you.
        </li>
        <li className="my-1 ml-4">
          (e) Any user, who avails any of the Services on our Platform, does
          solely at his own discretion, risk and responsibility. Fidential
          Insurance Brokers does not make any recommendations nor gives any
          warranty, whether implied or express, guarantee or otherwise with
          respect to the quality and functionality or a particular purpose.
        </li>
        <li className="my-1 ml-4">
          (f) Notwithstanding any other terms of these T&amp;Cs, the Company our
          directors, officers, employees, affiliates, agents, contractors,
          interns, suppliers, service providers or licensors (&ldquo;Company
          Representatives&rdquo;) shall not be liable for any injury, loss, claim, or
          any direct, indirect, incidental, punitive, special, or consequential
          damages of any kind, including, without limitation lost profits, lost
          revenue, lost savings, loss of data, replacement costs, or any similar
          damages, whether based in contract, tort (including negligence),
          strict liability or otherwise, arising from Your use of any of the
          Service, or arising from interruption of use or loss or corruption of
          data or for any other claim related in any way to Your use of the
          Service, including, but not limited to, any errors or omissions in any
          content, or any loss or damage of any kind incurred as a result of the
          use of the Service or any content posted, transmitted, or otherwise
          made available via the Service, even if advised of their possibility.
          In states or jurisdictions that do not allow the exclusion or the
          limitation of liability for consequential or incidental damages, in
          such states or jurisdictions, our liability shall be limited to the
          maximum extent permitted by law.
        </li>
        <li className="my-1 ml-4">
          (g) Notwithstanding any other terms of these T&amp;Cs, the liability of
          the Company towards any user of our Platform and/or the Service
          arising under or pursuant to these T&amp;Cs or on account of any other
          reason, shall at all times be limited to the amount of consideration
          or fees received by Us from such user for the Service.
        </li>
      </ul>
      <h3 className="font-semibold my-2">
        18. INTELLECTUAL PROPERTY AND PROPERITORY RIGHTS:
      </h3>
      <ul>
        <li className="my-1 ml-4">
          (a) Except as expressly stated in the T&amp;Cs, all information, content,
          material, trademarks, services marks, trade names, and trade secrets
          including but not limited to the software, text, images, graphics,
          video, script and audio, contained in the Platform and/or Services are
          proprietary property of the Company (&ldquo;Proprietary Information&rdquo;). No
          Proprietary Information may be copied, downloaded, reproduced,
          modified, republished, uploaded, posted, transmitted or distributed in
          any way without obtaining prior written permission of the Company and
          nothing on the Platform and/or Services shall be deemed to confer a
          license of or any other right, interest or title to or in any of the
          intellectual property rights belonging to the Company, to the User.
          The Company shall at all times retain full and complete title to the
          information, content or materials and all intellectual property rights
          inserted by the Company on such medium. The Platform and Services are
          protected by the copyright, trademark, patent and other applicable
          laws of India .
        </li>
        <li className="my-1 ml-4">
          (b) Subject to Your compliance with the T&amp;Cs, Company grants you a
          limited, non-exclusive, non-transferable, non-sublicensable license to
          use the Service during the term for which you have purchased a package
          (&ldquo;Service Term&rdquo;) . Except the right specifically mentioned herein, no
          right, title or interest shall be transferred to the User.
        </li>
        <li className="my-1 ml-4">
          (c) You will not remove, alter or obscure any copyright, trademark,
          service mark or other proprietary rights in or associated with the
          Platform and/or Services. All trademarks, service marks, logos, trade
          names, and any other proprietary designations of the Company used on
          or in connection with the Platform and Services are trademarks of the
          Company in India and abroad and are subject to the exclusive ownership
          of the Company.
        </li>
        <li className="my-1 ml-4">
          (d) Certain contents on the Platform may belong to third parties. Such
          contents have been reproduced after taking prior consent from said
          party and all rights relating to such content will remain with such
          third party. Further, You agree and acknowledge that the ownership of
          all trademarks, copyright, logos, service marks and other intellectual
          property owned by any third party shall continue to vest with such
          party. You are not permitted to use the same without the consent of
          the respective third party.
        </li>
      </ul>
      <h3 className="font-semibold my-2">19. INDEMNIFICATION:</h3>
      <ul>
        <li className="my-1 ml-4">
          (a) You agree to indemnify, defend and hold harmless Company and our
          parent, subsidiaries, affiliates, partners, officers, directors,
          agents, contractors, licensors, service providers, subcontractors,
          suppliers, interns and employees, harmless from and against any and
          all claims, losses, damages (actual and consequential), suits,
          judgments, litigation costs and attorneys&apos; fees, of every kind and
          nature, arising directly or indirectly on account of or pursuant to
          (i) Your use of the Platform and/or the Service; (ii) Your breach of
          these T&amp;Cs or the documents they incorporate by reference (including
          the P rivacy P olicy ); (iii) Your violation of any law or the rights
          of a third-party; (iv) any information posted by You on or through the
          Platform; (v) negligence, fraud, recklessness, harm or wilful
          misconduct on Your part; (vi) the infringement of the Intellectual
          Property Rights of WealthRight or a third party, arising from or in
          connection with the use of the Platform/Services.
        </li>
        <li className="my-1 ml-4">
          (b) Notwithstanding the above, in no event shall the Company be liable
          to you or to any third party for any losses or damages arising out of
          your use of the Platform or the Services, whether based on warranty,
          contract, tort (including negligence) or otherwise.
        </li>
        <li className="my-1 ml-4">
          (c) We will not accept any liability for any loss or damage (actual
          and consequential) resulting from or in connection with the use of the
          Platform and/or the inability to use it or for any loss or damage
          (actual and consequential) resulting from any delay or failure in the
          performance of the Service on account of any third party or person or
          due to any technical or technological failure or any other
          circumstances beyond Our control.
        </li>
      </ul>
      <h3 className="font-semibold my-2">20. SEVERABILITY :</h3>
      <ul>
        <li>
          If, for any reason, a court of competent jurisdiction finds any
          provision of the T&amp;Cs, or portion thereof, to be unenforceable, that
          provision shall be enforced to the maximum extent permissible so as to
          give effect to the intent of the parties as reflected by that
          provision, and the remainder of the T&amp;Cs shall continue in full force
          and effect.
        </li>
      </ul>
      <h3 className="font-semibold my-2">
        21. BREACH AND VIOLATION OF THE T&amp;Cs :
      </h3>
      <ul>
        <li className="my-1 ml-4">
          (a) In the event of any breach of these T&amp;Cs by the User, the User
          agrees that the Company will be irreparably harmed and may not have an
          adequate remedy in money or damages. The Company will be entitled to
          injunctive relief in addition to all applicable legal remedies.
        </li>
        <li className="my-1 ml-4">
          (b) Any violation of the T&amp;Cs or any other policy of the Company by
          the User may result in immediate suspension or termination of the User
          account apart from any legal remedy that the Company can avail as per
          the applicable law. The violation of these T&amp;Cs could also result in
          civil or criminal liability under applicable laws.
        </li>
      </ul>
      <h3 className="font-semibold my-2">22. CUSTOMER DUE DILIGENCE :</h3>
      <ul>
        <li className="my-1 ml-4">
          (a) You acknowledge and agree that, for any financial transaction
          conducted through the website, WealthRight may implement
          client/customer due diligence measures and request mandatory
          information necessary for KYC purposes, which you are obligated to
          provide. This is done while facilitating your insurance requirements
          with the insurance company(ies) in compliance with applicable laws and
          regulations. When necessary, you hereby give consent and authorize
          WealthRight to obtain your credit information through authorized
          entities. WealthRight may gather sufficient information to establish,
          to its satisfaction or that of the insurance company, the identity of
          each new customer and the intended nature of the insurance
          relationship between you and the insurance company(ies).
        </li>
        <li className="my-1 ml-4">
          (b) You also understand and agree that any payment toward insurance
          premiums should be made only through your bank account or from a joint
          bank account in which you are a joint holder. If the payment is made
          through a bank account not in your name (i.e., opened in the name of a
          third party), you acknowledge that WealthRight can conduct enhanced
          due diligence measures, including documentation, to meet customer due
          diligence requirements
        </li>
        <li className="my-1 ml-4">
          (c) Furthermore, you agree and acknowledge that, in compliance with
          the requirements and obligations under the PMLA Act and rules, all
          refunds will be processed by the insurance company(ies) through
          WealthRight to the bank account used for the payment of insurance
          premiums
        </li>
      </ul>
      <h3 className="font-semibold my-2">23. WAIVER AND ENTIRE AGREEMENT :</h3>
      <ul>
        <li>
          Our failure to exercise or enforce any right or provision of these
          T&amp;Cs shall not constitute a waiver of such right or provision. These
          T&amp;Cs and any policies or operating rules posted by Us on this Platform
          or in respect to The Service constitutes the entire agreement and
          understanding between You and Us and govern Your use of the Service,
          superseding any prior or contemporaneous agreements, communications
          and proposals, whether oral or written, between You and Us (including,
          but not limited to, any prior versions of the T&amp;Cs). Any ambiguities
          in the interpretation of these Terms of Service shall not be construed
          against the drafting party.
        </li>
      </ul>
      <h3 className="font-semibold my-2">
        24. GOVERNING LAW &amp; DISPUTE RESOLUTION:
      </h3>
      <ul>
        <li className="my-1 ml-4">
          (a) These T&amp;Cs and any separate agreements whereby we provide You
          Services shall be governed by and construed in accordance with the
          laws of India and subject to the arbitration provisions below, the
          Courts of [Mumbai] will have the sole and exclusive jurisdiction in
          case of any matter or dispute arising under or pursuant to these T&Cs.
          You expressly waive any express or implied objection to the same.
        </li>
        <li className="my-1 ml-4">
          (b) Negotiation and Arbitration: All differences or disputes between
          You and the Company relating to or arising out of or pertaining to
          these T&amp;Cs, which cannot be resolved amicably within 30 (thirty) days
          of the dispute having arisen, shall be referred to arbitration in
          accordance with the provisions of Arbitration and Conciliation Act,
          1996, as amended and/or restated from time to time. The arbitration
          shall be conducted by a sole arbitrator appointed mutually by the
          disputing parties. The seat and venue for the arbitration shall be
          [•]. The arbitrator’s award shall be final and binding upon the
          parties. The arbitration proceedings shall be conducted in the English
          language.
        </li>
      </ul>
      <h3 className="font-semibold my-2">25. FORCE MAJEURE :</h3>
      <ul>
        <li>
          We shall not be held liable for any of Our obligations under the T&amp;Cs
          due to reasons beyond our control such as down time of servers,
          viruses, strikes, technical snags, system compatibility, natural
          calamities, acts of war, terror etc. You agree not to hold Us liable
          for any delay or adverse effect caused due to the occurrence of such
          an event.
        </li>
      </ul>
      <h3 className="font-semibold my-2">26. CONTACT INFORMATION :</h3>
      <ul>
        <li>
          We attempt to make all best endeavours to provide our Users with a
          content, satisfying and enjoyable experience. In the unlikely event
          that you face any issues or wish to give any feedback, You can contact
          the Company at coordinates mentioned below :<br></br>
          Name:
          <br></br>
          Email:
          <br></br>
          http://wealth-right.com/
          <br></br>
          Tel: (India)
          <br></br>
          You acknowledge and agree to the T&amp;Cs and understand that they shall
          apply to your use of the Platform and Services. The Company has given
          you a reasonable opportunity to review these T&amp;Cs and after reviewing
          and understanding the T&amp;Cs, you have agreed to the same
        </li>
      </ul>
      <h3 className="font-semibold my-2">27. NOTICE</h3>
      <ul>
        <li>
          All notices served by the Company shall be provided via email to your
          account or as a general notification on the Platform as the Company
          may deem fit. Any notice to be provided to the Company should be sent
          to the registered office of the Company or via e-mail to
          http://wealth-right.com/ .
        </li>
      </ul>
      <h3 className="font-semibold my-2">28. HEADINGS</h3>
      <ul>
        <li>
          The headings used in these T&amp;Cs are included for convenience only and
          will not limit or otherwise affect these T&amp;Cs.
        </li>
      </ul>
    </div>
  );
}
