export default function TermsAndConditions() {
  return (
    <div className="container mx-auto mt-8 text-white">
      <h1 className="text-3xl font-bold mb-6">Terms and Conditions</h1>

      {/* T&C Content */}
      <div className="prose ">
        <p>
          THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF THE INFORMATION
          TECHNOLOGY ACT, 2000 AND RULES MADE THEREUNDER . THIS ELECTRONIC
          RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY
          PHYSICAL OR DIGITAL SIGNATURES. THESE TERMS ANDCONDITIONS (HEREINAFTER
          REFERRED TO AS “T&Cs”) WERE UPDATED ON 21 DECEMBER 2023 . PLEASE
          CAREFULLY READ THESE T&Cs . BY USING THIS PLATFORM YOU INDICATE YOUR
          UNDERSTANDING AND ACCEPTANCE OF THESE T&Cs. IF YOU DO NOT AGREE TO
          THESE T&Cs YOU MAY NOT USE THIS PLATFORM.
        </p>
        <br></br>

        {/* Definitions Section */}
        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">1. DEFINITIONS</h2>
          <p>
            In addition to other words and expressions that may be defined
            elsewhere in these T&Cs, unless the context otherwise requires, the
            following capitalized terms wherever used in these T&Cs shall have
            the meanings as ascribed hereunder:
          </p>
          <ul className="list-none pl-8">
            <li>
              (a)<strong>" Services"</strong> ” shall mean and refer to various
              services including but not limited to providing access to
              information primarily about Financial and Insurance products
              including but not restricted to Health Insurance, General
              Insurance, Life Insurance, Vehicle Insurance, mutual funds, fixed
              deposits and related services that are/ would be offered by the
              Company through the Platform.
            </li>
            <li>
              (b)<strong>"Intellectual Property Rights"</strong> shall mean any
              and all intellectual property rights belonging to and/or owned,
              used by a person in any parts of the world, whether registered or
              unregistered, including without limitation: (i) patents (whether
              utility or design); (ii) trademarks, service marks, logos, trade
              names and corporate names and the goodwill of the business
              symbolized; (iii) copyrights and copyrighted works; (iv) computer
              software, source code, data and documentation; (v) inventions,
              trade secrets, know-how, business intelligence and business
              information, whether patentable or non-patentable and whether or
              not reduced to practice; (vi) copyrightable works, specifications,
              etc., both printed and in electronic form; and (j) copies and
              tangible embodiments thereof.
            </li>
            <li>
              (c)<strong>"Privacy Policy"</strong> shall mean the privacy policy
              issued by the Company available on [•].
            </li>

            <li>
              <strong>“Users”, “You” or “Your”;</strong> shall mean any natural
              or legal person who has access to and is using the Platform for
              the purpose of availing the Services offered by the Company in
              accordance with these T&Cs. The term “Users” “You” or “Your” shall
              mean and include any other persons/entity who has not created a
              User Account and are accessing the Platform without such a User
              Account; an
            </li>
          </ul>
        </section>

        {/* Introduction Section */}
        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">2. INTRODUCTION</h2>
          <p>
            (a) Fidential Insurance Brokers Private Limited is a company
            incorporated under the Companies Act 2013...
          </p>
          {/* Add more content as needed */}
        </section>

        {/* Terms of Use Section */}
        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">3. TERMS OF USE</h2>
          <p>
            (a) The Company will provide Services to You subject to continuous
            compliance with the T&Cs stipulated in this document...
          </p>
          {/* Add more content as needed */}
        </section>

        {/* User Eligibility Section */}
        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">4. USER ELIGIBILITY</h2>
          <p>
            The Platform and Services can be accessed and used by those
            individuals or business entities...
          </p>
          {/* Add more content as needed */}
        </section>

        {/* User Conduct Section */}
        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">5. USER CONDUCT</h2>
          <p>
            (a) You represent that You are at least the age of majority in your
            state or province of residence and You have given Us...
          </p>
          {/* Add more content as needed */}
        </section>

        {/* Registration Section */}
        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">6. REGISTRATION</h2>
          <p>
            (a) In order to avail the Services and access and use the Platform,
            the User shall be required to register himself/herself...
          </p>
          {/* Add more content as needed */}
        </section>

        {/* Fees and Payment Section */}
        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">7. FEES AND PAYMENT</h2>
          <p>
            (a) The Company offers its Services via the Platform subject to the
            specified fees and charges...
          </p>
          {/* Add more content as needed */}
        </section>

        {/* Auto Renewal Section */}
        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">8. AUTO RENEWAL</h2>
          <p>
            (a) In order to ensure that you do not experience an interruption or
            loss of Service, Services may be offered on automatic renewal
            basis...
          </p>
          {/* Add more content as needed */}
        </section>

        {/* Cancellation of Services Section */}
        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">
            9. CANCELLATION OF SERVICES
          </h2>
          <p>
            (a) As per the IRDAI rules and regulations, you have the right to
            cancel your insurance policy within 15(fifteen) days...
          </p>
          {/* Add more content as needed */}
        </section>

        {/* Publicity Section */}
        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">10. PUBLICITY</h2>
          <p>
            You grant us the right to add your name and company logo to our
            customer list and on Our Platform.
          </p>
          {/* Add more content as needed */}
        </section>

        {/* Accuracy, Completeness, and Timeliness Section */}
        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">
            11. ACCURACY, COMPLETENESS AND TIMELINESS OF INFORMATION
          </h2>
          <p>
            (a) We are not responsible if information made available on the
            Platform is not accurate or not complete or not current...
          </p>
          {/* Add more content as needed */}
        </section>
      </div>
    </div>
  );
}
